### ISSUE TITLE
efinancialcareers request issue

### ISSUE THREAD

**Issue by nicolad** [nicolad/job-scraper#5]
![image](https://github.com/nicolad/job-scraper/assets/1477453/8350f871-87a7-43ed-8dfb-6f6ec9c9c640)

https://github.com/nicolad/job-scraper/pull/4

**Comment by prutonis** [comment]
Their site is down for an unknown reason

**Comment by prutonis** [comment]
Fixed with:
https://github.com/nicolad/job-scraper/commit/154d11a5f01f436b514a6d389f44229f3c3c3207

**Comment by nicolad** [comment]
nice job
